"""
Command Executor — parses and executes structured commands from the AI.
"""

import logging
from apps.planner.models import PlannerWorkspace, CanvasInstance
from .context_manager import ContextManager
from .memory_manager import MemoryManager
from .event_bus import event_bus, WorkspaceEventType

logger = logging.getLogger(__name__)


class CommandExecutor:
    """
    Executes structured commands generated by the AI provider.
    Commands are AI-independent and deterministic.
    """

    def __init__(self):
        self.context_manager = ContextManager()
        self.memory_manager = MemoryManager()
        self._handlers = {
            'SET_CONTEXT': self._handle_set_context,
            'SET_DATES': self._handle_set_dates,
            'SET_TRAVELERS': self._handle_set_travelers,
            'SET_BUDGET': self._handle_set_budget,
            'ADD_DESTINATION': self._handle_add_destination,
            'SET_TRAVEL_STYLE': self._handle_set_travel_style,
            'SET_INTERESTS': self._handle_set_interests,
            'OPEN_CANVAS': self._handle_open_canvas,
            'SEARCH_FLIGHTS': self._handle_search,
            'SEARCH_HOTELS': self._handle_search,
            'SEARCH_TRAINS': self._handle_search,
            'SEARCH_BUSES': self._handle_search,
            'SET_MODE': self._handle_set_mode,
            'RECALCULATE_PLAN': self._handle_recalculate,
            'GENERATE_RECOMMENDATIONS': self._handle_generate_recommendations,
        }

    def execute(self, workspace_id: str, commands: list[dict]) -> list[dict]:
        """
        Execute a list of commands.
        Returns list of execution results.
        """
        results = []

        for cmd in commands:
            cmd_type = cmd.get('type', '')
            payload = cmd.get('payload', {})

            handler = self._handlers.get(cmd_type)
            if handler:
                try:
                    result = handler(workspace_id, payload)
                    results.append({
                        'type': cmd_type,
                        'status': 'success',
                        'result': result,
                    })
                    logger.info(f"Command {cmd_type} executed for workspace {workspace_id}")
                except Exception as e:
                    logger.error(f"Command {cmd_type} failed: {e}")
                    results.append({
                        'type': cmd_type,
                        'status': 'error',
                        'error': str(e),
                    })
            else:
                logger.warning(f"Unknown command type: {cmd_type}")
                results.append({
                    'type': cmd_type,
                    'status': 'unknown',
                })

        # Update memory with command results
        self.memory_manager.update_from_commands(workspace_id, commands)

        return results

    # ─── Command Handlers ──────────────────────────────

    def _handle_set_context(self, workspace_id: str, payload: dict):
        updates = {}
        if 'destination' in payload:
            updates['destination_location'] = payload['destination']
        if 'origin' in payload:
            updates['origin_location'] = payload['origin']
        return self.context_manager.update_context(workspace_id, updates)

    def _handle_set_dates(self, workspace_id: str, payload: dict):
        return self.context_manager.update_context(workspace_id, {
            'start_date': payload.get('start_date'),
            'end_date': payload.get('end_date'),
        })

    def _handle_set_travelers(self, workspace_id: str, payload: dict):
        return self.context_manager.update_context(workspace_id, {
            'adults': payload.get('adults', 1),
            'children': payload.get('children', 0),
            'infants': payload.get('infants', 0),
        })

    def _handle_set_budget(self, workspace_id: str, payload: dict):
        return self.context_manager.update_context(workspace_id, {
            'budget': payload.get('amount'),
            'budget_currency': payload.get('currency', 'INR'),
        })

    def _handle_add_destination(self, workspace_id: str, payload: dict):
        return self.context_manager.update_context(workspace_id, {
            'destination_location': payload,
        })

    def _handle_set_travel_style(self, workspace_id: str, payload: dict):
        return self.context_manager.update_context(workspace_id, {
            'travel_style': payload.get('style', ''),
        })

    def _handle_set_interests(self, workspace_id: str, payload: dict):
        return self.context_manager.update_context(workspace_id, {
            'interests': payload.get('interests', []),
        })

    def _handle_open_canvas(self, workspace_id: str, payload: dict):
        canvas_type = payload.get('canvas_type', '')
        canvas, created = CanvasInstance.objects.get_or_create(
            workspace_id=workspace_id,
            canvas_type=canvas_type,
            defaults={'lifecycle_state': 'expanded', 'is_active': True},
        )
        if not created:
            canvas.lifecycle_state = 'expanded'
            canvas.is_active = True
            canvas.save()

        event_bus.publish(workspace_id, WorkspaceEventType.CANVAS_OPENED, {
            'canvas_type': canvas_type,
        })
        return {'canvas_type': canvas_type, 'state': 'expanded'}

    def _handle_search(self, workspace_id: str, payload: dict):
        """Handle SEARCH_FLIGHTS, SEARCH_HOTELS, etc. — opens canvas with pre-filled data."""
        canvas_map = {
            'SEARCH_FLIGHTS': 'flight',
            'SEARCH_HOTELS': 'hotel',
            'SEARCH_TRAINS': 'train',
            'SEARCH_BUSES': 'bus',
        }
        # Determine canvas type from the command type stored in caller context
        canvas_type = payload.get('canvas_type', 'flight')
        return self._handle_open_canvas(workspace_id, {'canvas_type': canvas_type, **payload})

    def _handle_set_mode(self, workspace_id: str, payload: dict):
        mode = payload.get('mode', 'planning')
        workspace = PlannerWorkspace.objects.get(id=workspace_id)
        workspace.mode = mode
        workspace.save(update_fields=['mode'])
        return {'mode': mode}

    def _handle_recalculate(self, workspace_id: str, payload: dict):
        event_bus.publish(workspace_id, WorkspaceEventType.PLAN_RECALCULATED, {})
        return {'status': 'recalculated'}

    def _handle_generate_recommendations(self, workspace_id: str, payload: dict):
        from .recommendation_engine import RecommendationEngine
        engine = RecommendationEngine()
        recs = engine.generate_recommendations(workspace_id)
        return {'count': len(recs)}
