# Generated by Django 6.0.6 on 2026-06-22 08:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VisaData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "country",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("visa_required", models.BooleanField(default=False)),
                ("visa_type", models.CharField(blank=True, max_length=100)),
                ("processing_time", models.CharField(blank=True, max_length=100)),
                ("processing_time_days", models.IntegerField(blank=True, null=True)),
                (
                    "fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("validity", models.CharField(blank=True, max_length=100)),
                (
                    "entry_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single Entry"),
                            ("MULTIPLE", "Multiple Entry"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("max_stay_duration", models.CharField(blank=True, max_length=100)),
                ("required_documents", models.JSONField(blank=True, default=list)),
                ("exemptions", models.JSONField(blank=True, default=list)),
                ("official_link", models.URLField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Visa Data",
                "ordering": ["country"],
                "indexes": [
                    models.Index(
                        fields=["country"], name="visa_visada_country_94e861_idx"
                    ),
                    models.Index(
                        fields=["visa_required"], name="visa_visada_visa_re_344cfb_idx"
                    ),
                ],
            },
        ),
    ]
