# Generated by Django 6.0.6 on 2026-06-22 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelPass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("FLIGHT", "Flight Ticket"),
                            ("TRAIN", "Train Ticket"),
                            ("BUS", "Bus Ticket"),
                            ("FERRY", "Ferry / Cruise"),
                            ("VISA", "Visa"),
                            ("HOTEL", "Hotel Booking"),
                            ("INSURANCE", "Travel Insurance"),
                            ("PASSPORT", "Passport Copy"),
                            ("OTHER", "Other Document"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("origin", models.CharField(blank=True, max_length=255)),
                ("destination", models.CharField(blank=True, max_length=255)),
                (
                    "document_path",
                    models.FileField(blank=True, null=True, upload_to="travel_passes/"),
                ),
                (
                    "pdf_path",
                    models.FileField(
                        blank=True, null=True, upload_to="travel_passes_pdf/"
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("reference_number", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("UPCOMING", "Upcoming"),
                            ("USED", "Used"),
                        ],
                        default="UPCOMING",
                        max_length=20,
                    ),
                ),
                ("issuer", models.CharField(blank=True, max_length=255)),
                ("seat_info", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_passes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "document_type"],
                        name="travelpass__user_id_eebf22_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="travelpass__user_id_424b02_idx"
                    ),
                ],
            },
        ),
    ]
