export const mockHotelResults = [
  {
    id: 1,
    name: 'The Taj Mahal Palace',
    rating: 4.8,
    reviews: 2547,
    stars: 5,
    location: 'Colaba, Mumbai',
    distance: '2.5 km from city center',
    image: '🏨',
    price: 12500,
    originalPrice: 15000,
    amenities: ['Free WiFi', 'Pool', 'Spa', 'Restaurant', 'Bar'],
    roomType: 'Deluxe Room',
    cancellation: 'Free cancellation',
    breakfast: 'Breakfast included'
  },
  {
    id: 2,
    name: 'Hotel Marine Plaza',
    rating: 4.3,
    reviews: 1823,
    stars: 4,
    location: 'Marine Drive, Mumbai',
    distance: '1.8 km from city center',
    image: '🏨',
    price: 6800,
    originalPrice: 8500,
    amenities: ['Free WiFi', 'Restaurant', 'Room Service'],
    roomType: 'Superior Room',
    cancellation: 'Free cancellation',
    breakfast: 'Breakfast included'
  },
  {
    id: 3,
    name: 'ITC Grand Central',
    rating: 4.6,
    reviews: 1456,
    stars: 5,
    location: 'Parel, Mumbai',
    distance: '3.2 km from city center',
    image: '🏨',
    price: 9500,
    originalPrice: 11000,
    amenities: ['Free WiFi', 'Pool', 'Gym', 'Restaurant', 'Spa'],
    roomType: 'Executive Room',
    cancellation: 'Free cancellation till 24h',
    breakfast: 'Breakfast included'
  },
  {
    id: 4,
    name: 'Hotel Suba Palace',
    rating: 4.0,
    reviews: 987,
    stars: 3,
    location: 'Andheri East, Mumbai',
    distance: '5.1 km from city center',
    image: '🏨',
    price: 3200,
    originalPrice: 4000,
    amenities: ['Free WiFi', 'Restaurant', 'Airport Shuttle'],
    roomType: 'Standard Room',
    cancellation: 'Non-refundable',
    breakfast: 'Breakfast extra ₹250'
  },
  {
    id: 5,
    name: 'Trident Nariman Point',
    rating: 4.5,
    reviews: 2134,
    stars: 5,
    location: 'Nariman Point, Mumbai',
    distance: '1.2 km from city center',
    image: '🏨',
    price: 11000,
    originalPrice: 13500,
    amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Bar', 'Concierge'],
    roomType: 'Premium Room',
    cancellation: 'Free cancellation',
    breakfast: 'Breakfast included'
  }
];
