# Generated by Django 6.0.6 on 2026-06-22 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Indira Gandhi International, New Delhi Railway Station",
                        max_length=200,
                    ),
                ),
                (
                    "city",
                    models.CharField(help_text="e.g., Delhi, Mumbai", max_length=100),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="e.g., DEL, NDLS", max_length=20
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("airport", "Airport"),
                            ("station", "Train Station"),
                            ("city", "City"),
                            ("bus_stop", "Bus Stop"),
                            ("poi", "Point of Interest"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("country", models.CharField(default="India", max_length=100)),
            ],
            options={
                "ordering": ["city", "name"],
                "indexes": [
                    models.Index(
                        fields=["location_type", "city"],
                        name="bookings_lo_locatio_3b8c92_idx",
                    ),
                    models.Index(fields=["code"], name="bookings_lo_code_8fbb57_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("flight", "Flight"),
                            ("train", "Train"),
                            ("hotel", "Hotel"),
                            ("bus", "Bus"),
                            ("cab", "Cab"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., IndiGo, Rajdhani Express, The Leela Palace",
                        max_length=200,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 6E-312 for flights, 12301 for trains",
                        max_length=50,
                    ),
                ),
                (
                    "origin_city",
                    models.CharField(
                        blank=True, help_text="e.g., Delhi, New Delhi", max_length=100
                    ),
                ),
                (
                    "destination_city",
                    models.CharField(
                        blank=True, help_text="e.g., Mumbai, Kolkata", max_length=100
                    ),
                ),
                (
                    "origin_code",
                    models.CharField(
                        blank=True,
                        help_text="IATA/Station code e.g., DEL, NDLS",
                        max_length=10,
                    ),
                ),
                (
                    "destination_code",
                    models.CharField(
                        blank=True,
                        help_text="IATA/Station code e.g., BOM, HWH",
                        max_length=10,
                    ),
                ),
                (
                    "departure_time",
                    models.CharField(
                        blank=True, help_text="e.g., 06:00", max_length=20
                    ),
                ),
                (
                    "arrival_time",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 08:15 or 09:55+1 for next day",
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="e.g., 2h 15m", max_length=50
                    ),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g., ["Mon", "Wed", "Fri"]',
                    ),
                ),
                (
                    "stops",
                    models.IntegerField(
                        default=0, help_text="0=Non-Stop, 1=1 Stop, etc."
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Service-specific data: cabin classes, train classes, hotel rooms, etc.",
                    ),
                ),
                (
                    "providers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {provider, price, deeplink} for comparison",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to hide from search results"
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Inventory",
                "verbose_name_plural": "Search Inventory",
                "ordering": ["service_type", "title"],
                "indexes": [
                    models.Index(
                        fields=["service_type", "is_active"],
                        name="bookings_se_service_021fc9_idx",
                    ),
                    models.Index(
                        fields=["origin_city", "destination_city"],
                        name="bookings_se_origin__f8238b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("flight", "Flight"),
                            ("train", "Train"),
                            ("bus", "Bus"),
                            ("hotel", "Hotel"),
                            ("cab", "Cab"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("details", models.JSONField()),
                ("payment_confirmed", models.BooleanField(default=False)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("provider", models.CharField(blank=True, max_length=100)),
                ("provider_booking_id", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="bookings_bo_user_id_69a5d5_idx"
                    ),
                    models.Index(
                        fields=["reference_number"],
                        name="bookings_bo_referen_77bb3b_idx",
                    ),
                ],
            },
        ),
    ]
