# Generated by Django 6.0.6 on 2026-06-22 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForexVendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("is_delivery_available", models.BooleanField(default=False)),
                ("opening_hours", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Forex Vendor",
                "verbose_name_plural": "Forex Vendors",
                "ordering": ["-rating"],
            },
        ),
        migrations.CreateModel(
            name="ForexData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("AED", "UAE Dirham"),
                            ("SGD", "Singapore Dollar"),
                            ("MYR", "Malaysian Ringgit"),
                            ("JPY", "Japanese Yen"),
                            ("AUD", "Australian Dollar"),
                            ("CAD", "Canadian Dollar"),
                        ],
                        db_index=True,
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("exchange_rate", models.DecimalField(decimal_places=6, max_digits=15)),
                ("base_currency", models.CharField(default="INR", max_length=3)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Forex Data",
                "ordering": ["currency"],
                "indexes": [
                    models.Index(
                        fields=["currency"], name="forex_forex_currenc_102096_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ForexDeliveryRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_currency",
                    models.CharField(
                        choices=[
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("AED", "UAE Dirham"),
                            ("SGD", "Singapore Dollar"),
                            ("MYR", "Malaysian Ringgit"),
                            ("JPY", "Japanese Yen"),
                            ("AUD", "Australian Dollar"),
                            ("CAD", "Canadian Dollar"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                (
                    "to_currency",
                    models.CharField(
                        choices=[
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("AED", "UAE Dirham"),
                            ("SGD", "Singapore Dollar"),
                            ("MYR", "Malaysian Ringgit"),
                            ("JPY", "Japanese Yen"),
                            ("AUD", "Australian Dollar"),
                            ("CAD", "Canadian Dollar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("exchange_rate", models.DecimalField(decimal_places=6, max_digits=15)),
                (
                    "converted_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("PICKUP", "Store Pickup"),
                            ("DELIVERY", "Home Delivery"),
                        ],
                        default="PICKUP",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("preferred_date", models.DateField()),
                ("preferred_time", models.TimeField()),
                ("contact_number", models.CharField(max_length=20)),
                ("delivery_address", models.TextField(blank=True)),
                (
                    "delivery_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "delivery_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forex_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_requests",
                        to="forex.forexvendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forex Delivery Request",
                "verbose_name_plural": "Forex Delivery Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorCurrencyInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("AED", "UAE Dirham"),
                            ("SGD", "Singapore Dollar"),
                            ("MYR", "Malaysian Ringgit"),
                            ("JPY", "Japanese Yen"),
                            ("AUD", "Australian Dollar"),
                            ("CAD", "Canadian Dollar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("exchange_rate", models.DecimalField(decimal_places=6, max_digits=15)),
                (
                    "quantity_available",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Available foreign currency quantity",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="forex.forexvendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Currency Inventory",
                "verbose_name_plural": "Vendor Currency Inventories",
                "ordering": ["currency"],
                "unique_together": {("vendor", "currency")},
            },
        ),
    ]
