[pytest]
# Tell pytest where your settings live. 
# Change 'config.settings.development' to wherever your actual local settings file is!
DJANGO_SETTINGS_MODULE = config.settings.development

# Optional but recommended: Tell pytest which file naming conventions to look for
python_files = tests.py test_*.py *_tests.py