# Generated by Django 6.0.6 on 2026-06-22 08:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIFeatureTile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("emoji", models.CharField(max_length=10)),
                ("cta_label", models.CharField(default="Try it →", max_length=50)),
                (
                    "cta_url",
                    models.CharField(
                        help_text="Internal path, e.g. /ai-planner", max_length=200
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "continent",
                    models.CharField(
                        choices=[
                            ("Asia", "Asia"),
                            ("Europe", "Europe"),
                            ("Africa", "Africa"),
                            ("North America", "North America"),
                            ("South America", "South America"),
                            ("Oceania", "Oceania"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                (
                    "price_inr",
                    models.PositiveIntegerField(help_text="Starting price in INR"),
                ),
                ("duration_days", models.PositiveSmallIntegerField()),
                ("mood_tags", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "booking_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Manually updated or synced from bookings"
                    ),
                ),
            ],
            options={
                "ordering": ["-view_count"],
            },
        ),
        migrations.CreateModel(
            name="MoodCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("emoji", models.CharField(max_length=10)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Mood Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SeasonalInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO 2-letter country code, e.g. IN", max_length=2
                    ),
                ),
                (
                    "continent",
                    models.CharField(
                        blank=True,
                        help_text="Continent-level fallback if country not matched",
                        max_length=50,
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(help_text="Month number 1–12"),
                ),
                ("tip_text", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["month"],
                "unique_together": {("country_code", "month")},
            },
        ),
    ]
