# Generated by Django 6.0.6 on 2026-07-10 19:47
# Split from the original 0001 — EntityEmbedding needs the pgvector
# extension, which isn't installed on this local Postgres yet (no MSVC
# toolchain to build it here). Everything else in the knowledge app has no
# vector dependency and applies cleanly now; see 0002_entityembedding.py.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("planner", "0010_plangenerationjob"),
        (
            "reference",
            "0007_transferprofile_activitymaster_accessibility_detail_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DistanceEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("origin_key", models.CharField(db_index=True, max_length=255)),
                ("destination_key", models.CharField(db_index=True, max_length=255)),
                ("mode", models.CharField(db_index=True, max_length=20)),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("duration_mins", models.FloatField(blank=True, null=True)),
                ("cost_estimate", models.JSONField(blank=True, null=True)),
                ("elevation_gain_m", models.FloatField(blank=True, null=True)),
                ("traffic_multiplier", models.FloatField(blank=True, null=True)),
                ("scenic_score", models.FloatField(blank=True, null=True)),
                ("carbon_kg", models.FloatField(blank=True, null=True)),
                ("source", models.CharField(max_length=30)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "unique_together": {("origin_key", "destination_key", "mode")},
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("service_type", models.CharField(max_length=40)),
                ("number", models.CharField(max_length=30)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_contacts",
                        to="reference.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="reference.country",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SafetyAdvisory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("normal", "normal"),
                            ("caution", "caution"),
                            ("high_risk", "high_risk"),
                        ],
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField()),
                ("source", models.CharField(max_length=120)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safety_advisories",
                        to="reference.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_advisories",
                        to="reference.country",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CrowdPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("object_id", models.CharField(max_length=64)),
                ("hour_of_day", models.PositiveSmallIntegerField()),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("weekday", "weekday"),
                            ("weekend", "weekend"),
                            ("holiday", "holiday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("crowd_level", models.FloatField()),
                ("sample_size", models.PositiveIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("telemetry", "telemetry"),
                            ("estimated_prior", "estimated_prior"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("content_type", "object_id", "hour_of_day", "day_type")
                },
            },
        ),
        migrations.CreateModel(
            name="EntityInteractionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("object_id", models.CharField(max_length=64)),
                ("event_type", models.CharField(max_length=30)),
                ("workspace_id", models.UUIDField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "created_at"],
                        name="knowledge_e_content_0bba93_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id", "event_type"],
                        name="knowledge_e_content_25ee65_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=60)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("venue_place_id", models.CharField(blank=True, max_length=255)),
                (
                    "venue_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "venue_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("source", models.CharField(default="manual", max_length=60)),
                ("cost_provenance", models.JSONField(blank=True, default=dict)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="reference.city",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["city", "start_date"],
                        name="knowledge_e_city_id_544de5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LocalTip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("object_id", models.CharField(max_length=64)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("scam_warning", "scam_warning"),
                            ("after_dark", "after_dark"),
                            ("etiquette", "etiquette"),
                            ("emergency_prep", "emergency_prep"),
                            ("safety", "safety"),
                            ("money", "money"),
                            ("transport", "transport"),
                            ("food", "food"),
                        ],
                        max_length=40,
                    ),
                ),
                ("tip_text", models.TextField()),
                ("source", models.CharField(blank=True, max_length=60)),
                ("source_url", models.URLField(blank=True)),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("verified", "verified"),
                            ("estimated", "estimated"),
                            ("suggested", "suggested"),
                        ],
                        default="suggested",
                        max_length=12,
                    ),
                ),
                ("needs_human_review", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="knowledge_l_content_7c1b07_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Neighbourhood",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("last_enriched_at", models.DateTimeField(blank=True, null=True)),
                ("enrichment_ttl_days", models.PositiveSmallIntegerField(default=30)),
                ("data_completeness_score", models.FloatField(default=0.0)),
                ("popularity_score", models.FloatField(db_index=True, default=0.0)),
                ("source", models.CharField(default="google_places", max_length=40)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("vibe_tags", models.JSONField(blank=True, default=list)),
                (
                    "center_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "center_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("safety_score", models.FloatField(blank=True, null=True)),
                ("price_tier", models.CharField(blank=True, max_length=10, null=True)),
                ("pace_tag", models.CharField(blank=True, max_length=20, null=True)),
                ("walkability_score", models.FloatField(blank=True, null=True)),
                ("local_rhythm_notes", models.TextField(blank=True)),
                (
                    "tourist_density_by_month",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighbourhoods",
                        to="reference.city",
                    ),
                ),
            ],
            options={
                "unique_together": {("city", "name")},
            },
        ),
        migrations.CreateModel(
            name="PlaceInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("object_id", models.CharField(max_length=64)),
                ("insight_type", models.CharField(max_length=40)),
                ("context_hash", models.CharField(db_index=True, max_length=64)),
                ("text", models.TextField(blank=True)),
                ("structured", models.JSONField(blank=True, default=dict)),
                ("provenance", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("content_type", "object_id", "insight_type", "context_hash")
                },
            },
        ),
        migrations.CreateModel(
            name="PlaceRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("from_object_id", models.CharField(max_length=64)),
                ("to_object_id", models.CharField(max_length=64)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("near", "near"),
                            ("pairs_well_with", "pairs_well_with"),
                            ("alternative_to", "alternative_to"),
                            ("on_route_between", "on_route_between"),
                        ],
                        max_length=30,
                    ),
                ),
                ("strength_score", models.FloatField(default=0.0)),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "from_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "to_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["from_content_type", "from_object_id"],
                        name="knowledge_p_from_co_e00caf_idx",
                    )
                ],
                "unique_together": {
                    (
                        "from_content_type",
                        "from_object_id",
                        "to_content_type",
                        "to_object_id",
                        "relation_type",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="PlanInsightDismissal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("context_hash", models.CharField(max_length=64)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_dismissals",
                        to="planner.plannerworkspace",
                    ),
                ),
            ],
            options={
                "unique_together": {("workspace", "context_hash")},
            },
        ),
        migrations.CreateModel(
            name="TransitOutcomeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("object_id", models.CharField(max_length=64)),
                ("scheduled_at", models.DateTimeField()),
                ("actual_at", models.DateTimeField(blank=True, null=True)),
                ("delta_minutes", models.IntegerField(blank=True, null=True)),
                ("source", models.CharField(max_length=40)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "scheduled_at"],
                        name="knowledge_t_content_9bb511_idx",
                    )
                ],
            },
        ),
    ]
