# Generated by Django 6.0.6 on 2026-07-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_entityembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="neighbourhood",
            name="external_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="neighbourhood",
            name="is_quarantined",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
