# Generated by Django 6.0.6 on 2026-07-18 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_neighbourhood_external_id_and_more"),
        ("reference", "0012_airport_hub_importance_airport_normalized_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="neighbourhood",
            name="locality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="neighbourhoods",
                to="reference.locality",
            ),
        ),
        migrations.AddField(
            model_name="neighbourhood",
            name="provenance_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="neighbourhood",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("verified", "Verified"),
                    ("unverified", "Unverified"),
                    ("quarantined", "Quarantined"),
                ],
                db_index=True,
                default="unverified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="neighbourhood",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
