# Generated by Django 6.0.6 on 2026-06-26 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusStation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=20)),
                (
                    "station_type",
                    models.CharField(
                        choices=[
                            ("isbt", "ISBT"),
                            ("depot", "Depot"),
                            ("stand", "Stand"),
                            ("terminal", "Terminal"),
                        ],
                        default="stand",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("population", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "is_major",
                    models.BooleanField(
                        default=False, help_text="Is a major/metro city"
                    ),
                ),
                ("timezone", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name_plural": "cities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "iso_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2", max_length=2, unique=True
                    ),
                ),
                (
                    "iso_code_3",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-3", max_length=3, unique=True
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        blank=True, help_text="Default ISO 4217 code", max_length=3
                    ),
                ),
                ("phone_code", models.CharField(blank=True, max_length=10)),
                (
                    "continent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("africa", "Africa"),
                            ("antarctica", "Antarctica"),
                            ("asia", "Asia"),
                            ("europe", "Europe"),
                            ("north_america", "North America"),
                            ("oceania", "Oceania"),
                            ("south_america", "South America"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timezone_default", models.CharField(blank=True, max_length=50)),
                ("flag_emoji", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "verbose_name_plural": "countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GooglePlaceCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("google_place_id", models.CharField(max_length=300, unique=True)),
                ("name", models.CharField(max_length=250)),
                ("address", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "types",
                    models.JSONField(
                        blank=True, default=list, help_text="Google place types"
                    ),
                ),
                (
                    "photos",
                    models.JSONField(
                        blank=True, default=list, help_text="Photo references"
                    ),
                ),
                ("opening_hours", models.JSONField(blank=True, default=dict)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True, max_length=500)),
                ("cached_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Google Place cache",
                "verbose_name_plural": "Google Place caches",
            },
        ),
        migrations.CreateModel(
            name="TimeZoneInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Asia/Kolkata", max_length=50, unique=True
                    ),
                ),
                (
                    "utc_offset",
                    models.CharField(help_text="e.g. +05:30", max_length=10),
                ),
                (
                    "dst_offset",
                    models.CharField(
                        blank=True, help_text="DST offset if applicable", max_length=10
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True, help_text="e.g. IST, EST", max_length=10
                    ),
                ),
            ],
            options={
                "verbose_name": "timezone",
                "verbose_name_plural": "timezones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("operator", models.CharField(blank=True, max_length=150)),
                (
                    "avg_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                (
                    "bus_type",
                    models.CharField(
                        choices=[
                            ("ordinary", "Ordinary"),
                            ("express", "Express"),
                            ("deluxe", "Deluxe"),
                            ("ac_sleeper", "AC Sleeper"),
                            ("volvo", "Volvo"),
                            ("semi_sleeper", "Semi Sleeper"),
                        ],
                        default="ordinary",
                        max_length=30,
                    ),
                ),
                (
                    "from_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_from",
                        to="reference.busstation",
                    ),
                ),
                (
                    "to_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_to",
                        to="reference.busstation",
                    ),
                ),
            ],
            options={
                "ordering": ["from_station__name"],
            },
        ),
        migrations.AddField(
            model_name="busstation",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bus_stations",
                to="reference.city",
            ),
        ),
        migrations.CreateModel(
            name="AttractionMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=250)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("monument", "Monument"),
                            ("temple", "Temple"),
                            ("museum", "Museum"),
                            ("park", "Park"),
                            ("beach", "Beach"),
                            ("fort", "Fort"),
                            ("palace", "Palace"),
                            ("market", "Market"),
                            ("viewpoint", "Viewpoint"),
                            ("zoo", "Zoo"),
                            ("waterfall", "Waterfall"),
                            ("lake", "Lake"),
                            ("garden", "Garden"),
                            ("religious", "Religious Site"),
                            ("historic", "Historic Site"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "entry_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("fee_currency", models.CharField(default="INR", max_length=3)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Recommended visit duration", null=True
                    ),
                ),
                ("opening_hours", models.JSONField(blank=True, default=dict)),
                (
                    "best_time",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Morning, October-March",
                        max_length=100,
                    ),
                ),
                ("images", models.JSONField(blank=True, default=list)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attractions",
                        to="reference.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "attraction",
                "verbose_name_plural": "attractions",
                "ordering": ["-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "iata_code",
                    models.CharField(
                        help_text="IATA 3-letter code", max_length=3, unique=True
                    ),
                ),
                (
                    "icao_code",
                    models.CharField(
                        blank=True, help_text="ICAO 4-letter code", max_length=4
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "display_name",
                    models.CharField(
                        blank=True, help_text="User-friendly name", max_length=200
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("timezone", models.CharField(blank=True, max_length=50)),
                ("is_international", models.BooleanField(default=False)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airports",
                        to="reference.city",
                    ),
                ),
            ],
            options={
                "ordering": ["iata_code"],
            },
        ),
        migrations.CreateModel(
            name="ActivityMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=250)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("adventure", "Adventure"),
                            ("water_sport", "Water Sport"),
                            ("cultural", "Cultural"),
                            ("food_tour", "Food Tour"),
                            ("nightlife", "Nightlife"),
                            ("wellness", "Wellness"),
                            ("shopping", "Shopping"),
                            ("photography", "Photography"),
                            ("wildlife", "Wildlife"),
                            ("trekking", "Trekking"),
                            ("cycling", "Cycling"),
                            ("cooking_class", "Cooking Class"),
                            ("workshop", "Workshop"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "price_range",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("budget", "Budget"),
                            ("mid_range", "Mid-range"),
                            ("premium", "Premium"),
                            ("luxury", "Luxury"),
                        ],
                        default="mid_range",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("challenging", "Challenging"),
                            ("extreme", "Extreme"),
                        ],
                        default="easy",
                        max_length=15,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=200)),
                ("booking_required", models.BooleanField(default=False)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("images", models.JSONField(blank=True, default=list)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="reference.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
                "ordering": ["-rating", "name"],
            },
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="reference.country",
            ),
        ),
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "iata_code",
                    models.CharField(
                        help_text="IATA 2-letter code", max_length=3, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("logo_url", models.URLField(blank=True, max_length=500)),
                (
                    "alliance",
                    models.CharField(
                        choices=[
                            ("star_alliance", "Star Alliance"),
                            ("oneworld", "Oneworld"),
                            ("skyteam", "SkyTeam"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                ("is_low_cost", models.BooleanField(default=False)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="airlines",
                        to="reference.country",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 code", max_length=3, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="currencies",
                        to="reference.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "currencies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="HolidayCalendar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("regional", "Regional"),
                            ("religious", "Religious"),
                            ("optional", "Optional"),
                        ],
                        default="national",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="reference.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "holiday",
                "verbose_name_plural": "holidays",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="HotelMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=250)),
                (
                    "stars",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Star"),
                            (3, "3 Star"),
                            (4, "4 Star"),
                            (5, "5 Star"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "hotel_type",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel"),
                            ("resort", "Resort"),
                            ("boutique", "Boutique"),
                            ("hostel", "Hostel"),
                            ("homestay", "Homestay"),
                            ("villa", "Villa"),
                            ("guesthouse", "Guesthouse"),
                            ("apartment", "Apartment"),
                        ],
                        default="hotel",
                        max_length=30,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True, default=list, help_text='e.g. ["pool","spa","wifi"]'
                    ),
                ),
                (
                    "price_range",
                    models.CharField(
                        choices=[
                            ("budget", "Budget"),
                            ("mid_range", "Mid-range"),
                            ("premium", "Premium"),
                            ("luxury", "Luxury"),
                        ],
                        default="mid_range",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, help_text="List of image URLs"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True, max_length=500)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotels",
                        to="reference.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "hotel",
                "verbose_name_plural": "hotels",
                "ordering": ["-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="MetroStation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "line",
                    models.CharField(
                        help_text="Line name e.g. Blue Line", max_length=100
                    ),
                ),
                (
                    "line_color",
                    models.CharField(
                        blank=True, help_text="Hex color e.g. #0000FF", max_length=7
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order on the line"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metro_stations",
                        to="reference.city",
                    ),
                ),
            ],
            options={
                "ordering": ["city", "line", "order"],
            },
        ),
        migrations.CreateModel(
            name="RailwayStation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Station code", max_length=10, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "station_type",
                    models.CharField(
                        choices=[
                            ("junction", "Junction"),
                            ("terminal", "Terminal"),
                            ("halt", "Halt"),
                            ("junction_terminal", "Junction Terminal"),
                        ],
                        default="junction",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True, help_text="Railway zone", max_length=20
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="railway_stations",
                        to="reference.city",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=250)),
                (
                    "cuisine_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Indian, Japanese, Italian",
                        max_length=100,
                    ),
                ),
                (
                    "price_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "₹"), (2, "₹₹"), (3, "₹₹₹"), (4, "₹₹₹₹")],
                        help_text="1=Budget, 4=Fine dining",
                        null=True,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("is_vegetarian_friendly", models.BooleanField(default=False)),
                (
                    "opening_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"mon": "09:00-22:00", "tue": "09:00-22:00"}',
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("images", models.JSONField(blank=True, default=list)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurants",
                        to="reference.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "restaurant",
                "verbose_name_plural": "restaurants",
                "ordering": ["-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="State/province code", max_length=10
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="reference.country",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("country", "name")},
            },
        ),
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="reference.state",
            ),
        ),
        migrations.CreateModel(
            name="TrainRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("train_name", models.CharField(max_length=150)),
                ("train_number", models.CharField(max_length=10)),
                (
                    "avg_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        blank=True, default=list, help_text="e.g. ['Mon','Wed','Fri']"
                    ),
                ),
                (
                    "classes",
                    models.JSONField(
                        blank=True, default=list, help_text="e.g. ['1A','2A','3A','SL']"
                    ),
                ),
                (
                    "from_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_from",
                        to="reference.railwaystation",
                    ),
                ),
                (
                    "to_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_to",
                        to="reference.railwaystation",
                    ),
                ),
            ],
            options={
                "ordering": ["train_number"],
            },
        ),
        migrations.CreateModel(
            name="TravelSeason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "season_type",
                    models.CharField(
                        choices=[
                            ("peak", "Peak Season"),
                            ("shoulder", "Shoulder Season"),
                            ("off_peak", "Off-Peak Season"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_month", models.PositiveSmallIntegerField(help_text="1-12")),
                ("end_month", models.PositiveSmallIntegerField(help_text="1-12")),
                ("description", models.TextField(blank=True)),
                (
                    "crowd_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        default="moderate",
                        max_length=15,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_seasons",
                        to="reference.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "travel season",
                "verbose_name_plural": "travel seasons",
                "ordering": ["city", "start_month"],
            },
        ),
        migrations.CreateModel(
            name="AirportRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "avg_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "avg_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("price_currency", models.CharField(default="INR", max_length=3)),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                (
                    "airlines",
                    models.ManyToManyField(
                        blank=True, related_name="routes", to="reference.airline"
                    ),
                ),
                (
                    "from_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_from",
                        to="reference.airport",
                    ),
                ),
                (
                    "to_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_to",
                        to="reference.airport",
                    ),
                ),
            ],
            options={
                "ordering": ["from_airport__iata_code", "to_airport__iata_code"],
                "unique_together": {("from_airport", "to_airport")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("country", "name")},
        ),
        migrations.CreateModel(
            name="VisaRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("visa_required", models.BooleanField(default=True)),
                (
                    "visa_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("e_visa", "E-Visa"),
                            ("on_arrival", "On Arrival"),
                            ("sticker", "Sticker Visa"),
                            ("visa_free", "Visa Free"),
                            ("eta", "ETA"),
                        ],
                        max_length=30,
                    ),
                ),
                ("processing_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("fee_currency", models.CharField(default="USD", max_length=3)),
                (
                    "validity",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 30 days, 90 days, 1 year",
                        max_length=100,
                    ),
                ),
                ("required_documents", models.JSONField(blank=True, default=list)),
                ("exemptions", models.JSONField(blank=True, default=list)),
                ("official_link", models.URLField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                (
                    "from_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visa_from",
                        to="reference.country",
                    ),
                ),
                (
                    "to_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visa_to",
                        to="reference.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "visa requirement",
                "verbose_name_plural": "visa requirements",
                "unique_together": {("from_country", "to_country")},
            },
        ),
        migrations.CreateModel(
            name="WeatherNormals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("month", models.PositiveSmallIntegerField(help_text="1-12")),
                (
                    "avg_temp_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="°C",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "avg_temp_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="°C",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "avg_rainfall_mm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "avg_humidity",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Percentage", null=True
                    ),
                ),
                (
                    "weather_description",
                    models.CharField(
                        blank=True, help_text="e.g. Hot and humid", max_length=200
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_normals",
                        to="reference.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "weather normals",
                "verbose_name_plural": "weather normals",
                "ordering": ["city", "month"],
                "unique_together": {("city", "month")},
            },
        ),
    ]
