# Generated by Django 6.0.6 on 2026-07-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitymaster",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="attractionmaster",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="hotelmaster",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="restaurantmaster",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
