# Generated by Django 6.0.6 on 2026-07-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0002_alter_activitymaster_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantmaster",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="allows_dogs",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="delivery",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="dine_in",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="editorial_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="good_for_children",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="good_for_groups",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="menu_for_children",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="national_phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="opening_hours",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="outdoor_seating",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="parking_options",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="payment_options",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="place_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="price_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="primary_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="reviews",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="secondary_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="serves_vegetarian_food",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="takeout",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="user_ratings_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="website_uri",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
