# Generated by Django 6.0.6 on 2026-07-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0003_restaurantmaster_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitymaster",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="difficulty_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="editorial_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="equipment_included",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="good_for_children",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="good_for_groups",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="guided_tour",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="national_phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="opening_hours",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="place_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="primary_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="reviews",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="secondary_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="suggested_duration",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="user_rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="user_ratings_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="website_uri",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="editorial_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="good_for_children",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="good_for_groups",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="national_phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="opening_hours",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="parking_options",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="place_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="primary_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="reviews",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="secondary_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="ticket_price_estimate",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="user_ratings_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="website_uri",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="wheelchair_accessible",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
