# Generated by Django 6.0.6 on 2026-07-08 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0004_activitymaster_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("flight", "Flight"),
                            ("train", "Train"),
                            ("bus", "Bus"),
                            ("hotel", "Hotel"),
                            ("cab", "Cab"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("provider", models.CharField(db_index=True, max_length=100)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Flight number, train number, room type, cab type",
                        max_length=50,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra details like class breakdown, seat availability, duration, departure/arrival times",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "airport_route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_prices",
                        to="reference.airportroute",
                    ),
                ),
                (
                    "bus_route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_prices",
                        to="reference.busroute",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cab_historical_prices",
                        to="reference.city",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_prices",
                        to="reference.hotelmaster",
                    ),
                ),
                (
                    "train_route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_prices",
                        to="reference.trainroute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Travel Price History",
                "verbose_name_plural": "Travel Price History",
                "ordering": ["date", "service_type", "provider"],
                "indexes": [
                    models.Index(
                        fields=["service_type", "date"],
                        name="reference_t_service_215f47_idx",
                    )
                ],
            },
        ),
    ]
