# Generated by Django 6.0.6 on 2026-07-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0005_travelpricehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelmaster",
            name="editorial_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="national_phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="opening_hours",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="parking_options",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="payment_options",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="place_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="price_range",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="primary_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="reviews",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="secondary_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="user_ratings_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="website_uri",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
