# Generated by Django 6.0.6 on 2026-07-10 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0006_hotelmaster_editorial_summary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_code", models.CharField(max_length=10, unique=True)),
                (
                    "typical_min_connection_mins",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("terminal_change_common", models.BooleanField(default=False)),
                ("stair_heavy", models.BooleanField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "source",
                    models.CharField(default="general_knowledge", max_length=40),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="accessibility_detail",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="data_completeness_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="enrichment_ttl_days",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="last_enriched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="popularity_score",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="source",
            field=models.CharField(default="google_places", max_length=40),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="accessibility_detail",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="data_completeness_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="enrichment_ttl_days",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="last_enriched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="popularity_score",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="source",
            field=models.CharField(default="google_places", max_length=40),
        ),
        migrations.AddField(
            model_name="city",
            name="place_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="data_completeness_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="enrichment_ttl_days",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="last_enriched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="popularity_score",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="seasonal_amenities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="source",
            field=models.CharField(default="google_places", max_length=40),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="data_completeness_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="dietary_accommodations",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="enrichment_ttl_days",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="last_enriched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="popularity_score",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="reservation_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("walk_in", "walk_in"),
                    ("recommended", "recommended"),
                    ("required", "required"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="source",
            field=models.CharField(default="google_places", max_length=40),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="typical_lead_time_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="travelpricehistory",
            name="provenance_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("verified", "verified"),
                    ("estimated", "estimated"),
                    ("suggested", "suggested"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="travelseason",
            name="natural_phenomena",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="visarequirement",
            name="document_checklist",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="visarequirement",
            name="processing_time_max_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visarequirement",
            name="processing_time_min_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weathernormals",
            name="feels_like_bucket",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="weathernormals",
            name="packing_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("name", "state", "country")},
        ),
        migrations.AlterUniqueTogether(
            name="travelseason",
            unique_together={("city", "month")},
        ),
        migrations.AlterUniqueTogether(
            name="weathernormals",
            unique_together={("city", "month")},
        ),
        migrations.CreateModel(
            name="HotelRoomTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tier_name", models.CharField(max_length=120)),
                ("price_premium_pct", models.FloatField(blank=True, null=True)),
                ("feature_tags", models.JSONField(blank=True, default=list)),
                (
                    "source",
                    models.CharField(default="provider_rate_data", max_length=40),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_tiers",
                        to="reference.hotelmaster",
                    ),
                ),
            ],
        ),
    ]
