# Generated by Django 6.0.6 on 2026-07-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reference",
            "0007_transferprofile_activitymaster_accessibility_detail_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Currency",
        ),
        migrations.DeleteModel(
            name="GooglePlaceCache",
        ),
        migrations.DeleteModel(
            name="VisaRequirement",
        ),
    ]
