# Generated by Django 6.0.6 on 2026-07-18 20:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("reference", "0011_railwaystation_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="hub_importance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("minor", "Minor"),
                ],
                default="minor",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="airport",
            name="normalized_code",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name="airport",
            name="normalized_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="busstation",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="busstation",
            name="hub_importance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("minor", "Minor"),
                ],
                default="minor",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="busstation",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="busstation",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="busstation",
            name="normalized_code",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name="busstation",
            name="normalized_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="city",
            name="normalized_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="railwaystation",
            name="derived_connectivity_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="railwaystation",
            name="derived_hub_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="railwaystation",
            name="derived_intelligence_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="railwaystation",
            name="network_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary_city_hub", "Primary city hub"),
                    ("secondary_city_hub", "Secondary city hub"),
                    ("regional_hub", "Regional hub"),
                    ("local_station", "Local station"),
                    ("interchange", "Interchange"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="railwaystation",
            name="normalized_code",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name="railwaystation",
            name="normalized_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="railwaystation",
            name="operational_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("terminal", "Terminal"),
                    ("through_station", "Through station"),
                    ("junction", "Junction"),
                    ("halt", "Halt"),
                    ("suburban", "Suburban"),
                    ("metro", "Metro"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="travelpricehistory",
            name="classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("provider_observation", "Provider observation"),
                    (
                        "historical_dataset_observation",
                        "Historical dataset observation",
                    ),
                    ("cached_live_response", "Cached live response"),
                    ("calculated_estimate", "Calculated estimate"),
                    ("mock_data", "Mock data"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=40,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CityAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias_name", models.CharField(db_index=True, max_length=255)),
                ("normalized_alias", models.CharField(db_index=True, max_length=255)),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("official", "Official name"),
                            ("common", "Common name"),
                            ("old", "Old/historical name"),
                            ("local_language", "Local language name"),
                            ("alternate_spelling", "Alternate English spelling"),
                            ("airport_name", "Airport-style city name"),
                            ("railway_search", "Railway search spelling"),
                            ("provider_specific", "Provider-specific name"),
                            ("abbreviation", "Abbreviation"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                (
                    "language_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("provider", models.CharField(blank=True, max_length=60, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("source", models.CharField(default="curated", max_length=40)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("unverified", "Unverified"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="reference.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Locality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "normalized_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "locality_type",
                    models.CharField(
                        choices=[
                            ("district", "District"),
                            ("neighbourhood", "Neighbourhood"),
                            ("business_district", "Business district"),
                            ("tourism_district", "Tourism district"),
                            ("old_city", "Old city"),
                            ("airport_area", "Airport area"),
                            ("railway_area", "Railway station area"),
                            ("suburb", "Suburb"),
                            ("satellite_city", "Satellite city"),
                            ("administrative_zone", "Administrative zone"),
                        ],
                        default="district",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "external_place_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "tourism_importance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("emerging", "Emerging"),
                            ("niche", "Niche"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("transfer_relevance", models.BooleanField(default=False)),
                ("source", models.CharField(default="curated", max_length=40)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("unverified", "Unverified"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localities",
                        to="reference.city",
                    ),
                ),
                (
                    "parent_locality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_localities",
                        to="reference.locality",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocalityAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias_name", models.CharField(db_index=True, max_length=255)),
                ("normalized_alias", models.CharField(db_index=True, max_length=255)),
                ("alias_type", models.CharField(default="common", max_length=20)),
                (
                    "language_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("provider", models.CharField(blank=True, max_length=60, null=True)),
                ("source", models.CharField(default="curated", max_length=40)),
                (
                    "verification_status",
                    models.CharField(default="unverified", max_length=20),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "locality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="reference.locality",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetroArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "normalized_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("timezone", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("source", models.CharField(default="curated", max_length=40)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("unverified", "Unverified"),
                            ("quarantined", "Quarantined"),
                        ],
                        db_index=True,
                        default="unverified",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metro_areas",
                        to="reference.country",
                    ),
                ),
                (
                    "primary_city",
                    models.ForeignKey(
                        blank=True,
                        help_text="The city most users mean when they name this metro area",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_for_metro",
                        to="reference.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusStationServiceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_km", models.FloatField(blank=True, null=True)),
                (
                    "distance_type",
                    models.CharField(
                        choices=[
                            ("straight_line", "Straight line"),
                            ("road", "Road distance"),
                            ("rail", "Rail distance"),
                            ("walking", "Walking distance"),
                            ("provider_reported", "Provider reported"),
                        ],
                        default="straight_line",
                        max_length=30,
                    ),
                ),
                (
                    "typical_transfer_mins",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "transfer_mode",
                    models.CharField(
                        choices=[
                            ("cab", "Cab"),
                            ("metro", "Metro"),
                            ("bus", "Bus"),
                            ("walk", "Walk"),
                            ("mixed", "Mixed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "traffic_context",
                    models.CharField(
                        choices=[
                            ("normal", "Normal traffic"),
                            ("peak", "Peak traffic"),
                            ("off_peak", "Off-peak traffic"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("is_primary_hub", models.BooleanField(default=False)),
                ("is_estimated", models.BooleanField(default=True)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(default="derived", max_length=40)),
                ("confidence", models.FloatField(default=0.5)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bus_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_areas",
                        to="reference.busstation",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reference.city"
                    ),
                ),
                (
                    "locality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reference.locality",
                    ),
                ),
                (
                    "metro_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reference.metroarea",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AirportServiceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_km", models.FloatField(blank=True, null=True)),
                (
                    "distance_type",
                    models.CharField(
                        choices=[
                            ("straight_line", "Straight line"),
                            ("road", "Road distance"),
                            ("rail", "Rail distance"),
                            ("walking", "Walking distance"),
                            ("provider_reported", "Provider reported"),
                        ],
                        default="straight_line",
                        max_length=30,
                    ),
                ),
                (
                    "typical_transfer_mins",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "transfer_mode",
                    models.CharField(
                        choices=[
                            ("cab", "Cab"),
                            ("metro", "Metro"),
                            ("bus", "Bus"),
                            ("walk", "Walk"),
                            ("mixed", "Mixed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "traffic_context",
                    models.CharField(
                        choices=[
                            ("normal", "Normal traffic"),
                            ("peak", "Peak traffic"),
                            ("off_peak", "Off-peak traffic"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("is_primary_hub", models.BooleanField(default=False)),
                ("is_estimated", models.BooleanField(default=True)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(default="derived", max_length=40)),
                ("confidence", models.FloatField(default=0.5)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_areas",
                        to="reference.airport",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reference.city"
                    ),
                ),
                (
                    "locality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reference.locality",
                    ),
                ),
                (
                    "metro_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reference.metroarea",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MetroAreaAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias_name", models.CharField(db_index=True, max_length=255)),
                ("normalized_alias", models.CharField(db_index=True, max_length=255)),
                ("alias_type", models.CharField(default="common", max_length=20)),
                ("source", models.CharField(default="curated", max_length=40)),
                (
                    "metro_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="reference.metroarea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetroAreaCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("core", "Core city"),
                            ("satellite", "Satellite city"),
                            ("suburb", "Suburb"),
                            ("commuter_city", "Commuter city"),
                            ("airport_city", "Airport city"),
                            ("cross_border", "Cross-border/Special classification"),
                        ],
                        default="core",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("source", models.CharField(default="curated", max_length=40)),
                ("confidence", models.FloatField(default=1.0)),
                (
                    "verification_status",
                    models.CharField(default="unverified", max_length=20),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metro_memberships",
                        to="reference.city",
                    ),
                ),
                (
                    "metro_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_cities",
                        to="reference.metroarea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RailwayStationServiceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_km", models.FloatField(blank=True, null=True)),
                (
                    "distance_type",
                    models.CharField(
                        choices=[
                            ("straight_line", "Straight line"),
                            ("road", "Road distance"),
                            ("rail", "Rail distance"),
                            ("walking", "Walking distance"),
                            ("provider_reported", "Provider reported"),
                        ],
                        default="straight_line",
                        max_length=30,
                    ),
                ),
                (
                    "typical_transfer_mins",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "transfer_mode",
                    models.CharField(
                        choices=[
                            ("cab", "Cab"),
                            ("metro", "Metro"),
                            ("bus", "Bus"),
                            ("walk", "Walk"),
                            ("mixed", "Mixed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "traffic_context",
                    models.CharField(
                        choices=[
                            ("normal", "Normal traffic"),
                            ("peak", "Peak traffic"),
                            ("off_peak", "Off-peak traffic"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("is_primary_hub", models.BooleanField(default=False)),
                ("is_estimated", models.BooleanField(default=True)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(default="derived", max_length=40)),
                ("confidence", models.FloatField(default=0.5)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reference.city"
                    ),
                ),
                (
                    "locality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reference.locality",
                    ),
                ),
                (
                    "metro_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reference.metroarea",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_areas",
                        to="reference.railwaystation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReferenceFieldProvenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(db_index=True, max_length=64)),
                ("field_name", models.CharField(max_length=100)),
                ("source_name", models.CharField(max_length=100)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("retrieved_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("confidence", models.FloatField(default=0.5)),
                (
                    "provenance_tier",
                    models.CharField(
                        choices=[
                            ("authoritative", "Authoritative source"),
                            ("provider", "Verified provider"),
                            ("open_dataset", "Reputable open dataset"),
                            ("derived", "Calculated/derived"),
                            ("suggested", "LLM-suggested/estimated"),
                            ("quarantined", "Quarantined/uncertain"),
                        ],
                        default="derived",
                        max_length=20,
                    ),
                ),
                (
                    "raw_value_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_current", models.BooleanField(default=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TravelPriceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("flight", "Flight"),
                            ("train", "Train"),
                            ("bus", "Bus"),
                            ("hotel", "Hotel"),
                            ("cab", "Cab"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("observed_date", models.DateField(db_index=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("provider", models.CharField(db_index=True, max_length=100)),
                ("code", models.CharField(blank=True, max_length=50)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("live_api", "Live API fetch"),
                            ("historical_import", "Historical data import"),
                            ("provider_cache", "Provider cache"),
                        ],
                        default="live_api",
                        max_length=20,
                    ),
                ),
                ("retrieved_at", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "airport_route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_observations",
                        to="reference.airportroute",
                    ),
                ),
                (
                    "bus_route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_observations",
                        to="reference.busroute",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cab_price_observations",
                        to="reference.city",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_observations",
                        to="reference.hotelmaster",
                    ),
                ),
                (
                    "train_route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_observations",
                        to="reference.trainroute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TravelPriceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("flight", "Flight"),
                            ("train", "Train"),
                            ("bus", "Bus"),
                            ("hotel", "Hotel"),
                            ("cab", "Cab"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "median_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "p25_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "p75_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_band",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("budget", "Budget"),
                            ("moderate", "Moderate"),
                            ("premium", "Premium"),
                            ("luxury", "Luxury"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("seasonal_index", models.FloatField(blank=True, null=True)),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("observation_period_start", models.DateField()),
                ("observation_period_end", models.DateField()),
                ("sample_count", models.PositiveIntegerField(default=0)),
                ("calculation_date", models.DateField(auto_now=True)),
                ("algorithm_version", models.CharField(default="v1", max_length=20)),
                ("source_coverage", models.CharField(blank=True, max_length=255)),
                ("confidence", models.FloatField(default=0.5)),
                ("includes_taxes", models.BooleanField(default=False)),
                (
                    "destination_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_summaries_destination",
                        to="reference.city",
                    ),
                ),
                (
                    "origin_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_summaries_origin",
                        to="reference.city",
                    ),
                ),
            ],
        ),
    ]
