# Generated by Django 6.0.6 on 2026-07-19 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("reference", "0013_phase2_geospatial_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("publisher", models.CharField(max_length=255)),
                ("licence_name", models.CharField(max_length=120)),
                ("licence_url", models.URLField(blank=True, max_length=500, null=True)),
                ("licence_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "storage_permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="e.g. {'raw': true, 'normalized': true}",
                    ),
                ),
                ("attribution_text", models.TextField(blank=True)),
                ("priority_rank", models.PositiveSmallIntegerField(default=100)),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Importers must refuse to run against an inactive source.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Source registry",
                "ordering": ["priority_rank", "slug"],
            },
        ),
        migrations.AddField(
            model_name="airport",
            name="ourairports_ident",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="airport",
            name="wikidata_id",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="destination_tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="city",
            name="geonameid",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="city",
            name="population",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="wikidata_id",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="railwaystation",
            name="wikidata_id",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="DataQualityIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(db_index=True, max_length=64)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("coordinate_conflict", "Coordinate conflict"),
                            ("duplicate_candidate", "Duplicate candidate"),
                            ("identity_conflict", "Identity conflict"),
                            ("licence_block", "Licence block"),
                            ("coordinate_out_of_range", "Coordinate out of range"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("accepted", "Accepted"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lgd_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "normalized_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("source", models.CharField(default="geonames_adm2", max_length=40)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="reference.state",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "state")},
            },
        ),
        migrations.AddField(
            model_name="city",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cities",
                to="reference.district",
            ),
        ),
        migrations.CreateModel(
            name="SourceRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_label", models.CharField(blank=True, max_length=100)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("file_checksum", models.CharField(blank=True, max_length=128)),
                ("record_count", models.PositiveIntegerField(blank=True, null=True)),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="reference.sourceregistry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command_name", models.CharField(max_length=100)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("dry_run", "Dry run"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("dry_run", models.BooleanField(default=True)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("conflicted_count", models.PositiveIntegerField(default=0)),
                ("quarantined_count", models.PositiveIntegerField(default=0)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="reference.sourcerelease",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StagingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "source_record_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("normalized_payload", models.JSONField(blank=True, default=dict)),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("unmatched", "Unmatched"),
                            ("matched", "Matched"),
                            ("ambiguous", "Ambiguous"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="unmatched",
                        max_length=20,
                    ),
                ),
                (
                    "matched_object_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("match_confidence", models.FloatField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staging_records",
                        to="reference.importbatch",
                    ),
                ),
                (
                    "matched_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderEntityMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(db_index=True, max_length=64)),
                ("external_id", models.CharField(db_index=True, max_length=255)),
                ("matched_at", models.DateTimeField(auto_now_add=True)),
                ("match_confidence", models.FloatField(default=1.0)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_maps",
                        to="reference.sourceregistry",
                    ),
                ),
            ],
            options={
                "unique_together": {("source", "external_id")},
            },
        ),
    ]
