# Generated by Django 6.0.6 on 2026-07-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("reference", "0014_phase3_source_registry"),
    ]

    operations = [
        migrations.AddField(
            model_name="airportroute",
            name="confidence",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="airportroute",
            name="distance_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="airportroute",
            name="frequency_per_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="airportroute",
            name="freshness_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="airportroute",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="airportroute",
            name="operating_days",
            field=models.CharField(default="1111111", max_length=7),
        ),
        migrations.AddField(
            model_name="airportroute",
            name="provenance_tier",
            field=models.CharField(
                choices=[
                    ("authoritative", "Authoritative source"),
                    ("provider", "Verified provider"),
                    ("open_dataset", "Reputable open dataset"),
                    ("derived", "Calculated/derived"),
                    ("suggested", "LLM-suggested/estimated"),
                    ("quarantined", "Quarantined/uncertain"),
                ],
                default="derived",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="airportroute",
            name="service_class_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="busroute",
            name="confidence",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="busroute",
            name="distance_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="busroute",
            name="frequency_per_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="busroute",
            name="freshness_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="busroute",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="busroute",
            name="operating_days",
            field=models.CharField(default="1111111", max_length=7),
        ),
        migrations.AddField(
            model_name="busroute",
            name="provenance_tier",
            field=models.CharField(
                choices=[
                    ("authoritative", "Authoritative source"),
                    ("provider", "Verified provider"),
                    ("open_dataset", "Reputable open dataset"),
                    ("derived", "Calculated/derived"),
                    ("suggested", "LLM-suggested/estimated"),
                    ("quarantined", "Quarantined/uncertain"),
                ],
                default="derived",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="busroute",
            name="service_class_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="trainroute",
            name="confidence",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="trainroute",
            name="distance_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainroute",
            name="frequency_per_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainroute",
            name="freshness_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainroute",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="trainroute",
            name="operating_days",
            field=models.CharField(default="1111111", max_length=7),
        ),
        migrations.AddField(
            model_name="trainroute",
            name="provenance_tier",
            field=models.CharField(
                choices=[
                    ("authoritative", "Authoritative source"),
                    ("provider", "Verified provider"),
                    ("open_dataset", "Reputable open dataset"),
                    ("derived", "Calculated/derived"),
                    ("suggested", "LLM-suggested/estimated"),
                    ("quarantined", "Quarantined/uncertain"),
                ],
                default="derived",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trainroute",
            name="service_class_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="HubTransferLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_object_id", models.CharField(db_index=True, max_length=64)),
                ("to_object_id", models.CharField(db_index=True, max_length=64)),
                ("distance_km", models.FloatField(blank=True, null=True)),
                (
                    "typical_transfer_mins",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("cab", "Cab"),
                            ("metro", "Metro"),
                            ("walk", "Walk"),
                            ("mixed", "Mixed"),
                        ],
                        default="cab",
                        max_length=20,
                    ),
                ),
                (
                    "min_connection_mins",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "provenance_tier",
                    models.CharField(
                        choices=[
                            ("authoritative", "Authoritative source"),
                            ("provider", "Verified provider"),
                            ("open_dataset", "Reputable open dataset"),
                            ("derived", "Calculated/derived"),
                            ("suggested", "LLM-suggested/estimated"),
                            ("quarantined", "Quarantined/uncertain"),
                        ],
                        default="derived",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0.5)),
                (
                    "from_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "to_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "from_content_type",
                        "from_object_id",
                        "to_content_type",
                        "to_object_id",
                    )
                },
            },
        ),
    ]
