# Generated by Django 6.0.6 on 2026-07-19 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0015_phase4_route_graph"),
    ]

    operations = [
        migrations.CreateModel(
            name="FareRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("train", "Train"),
                            ("bus", "Bus"),
                            ("cab", "Cab"),
                            ("metro", "Metro"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human label, e.g. 'UPSRTC Ordinary Bus'",
                        max_length=255,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("national", "National default"),
                            ("state", "State-specific"),
                            ("city_tier", "City-tier"),
                            ("route", "Specific route"),
                        ],
                        default="national",
                        max_length=20,
                    ),
                ),
                (
                    "service_class",
                    models.CharField(
                        blank=True,
                        help_text="e.g. sleeper/3ac/2ac/1ac for train, non_ac/ac for bus, hatchback/sedan/suv for cab.",
                        max_length=40,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("per_km", "Per km"),
                            ("flat", "Flat fare"),
                            ("per_day", "Per day"),
                        ],
                        default="per_km",
                        max_length=20,
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="e.g. {'base_fare': 300, 'per_km': 16} or a distance-slab list.",
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "provenance_tier",
                    models.CharField(
                        choices=[
                            ("authoritative", "Authoritative source"),
                            ("provider", "Verified provider"),
                            ("open_dataset", "Reputable open dataset"),
                            ("derived", "Calculated/derived"),
                            ("suggested", "LLM-suggested/estimated"),
                            ("quarantined", "Quarantined/uncertain"),
                        ],
                        default="derived",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0.5)),
                ("freshness_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for state/city-tier/route-scoped rules; null for a national default.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fare_rules",
                        to="reference.city",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fare_rules",
                        to="reference.sourceregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fare rule",
                "verbose_name_plural": "Fare rules",
                "ordering": ["category", "scope", "-valid_from"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="ref_farerule_cat_active_idx",
                    )
                ],
            },
        ),
    ]
