# Generated by Django 6.0.6 on 2026-07-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0016_phase5_price_estimation"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitymaster",
            name="image_attribution",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="image_license",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'CC-BY-SA 4.0' — set only for images with a known open licence (Wikimedia), never for Google Photos.",
                max_length=60,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="image_source",
            field=models.URLField(
                blank=True,
                help_text="Link to the licensed image's source page (e.g. a Wikimedia Commons file page).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="osm_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="OSM 'type/id' form, e.g. 'way/123456789'.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activitymaster",
            name="wikidata_id",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="image_attribution",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="image_license",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'CC-BY-SA 4.0' — set only for images with a known open licence (Wikimedia), never for Google Photos.",
                max_length=60,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="image_source",
            field=models.URLField(
                blank=True,
                help_text="Link to the licensed image's source page (e.g. a Wikimedia Commons file page).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="osm_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="OSM 'type/id' form, e.g. 'way/123456789'.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attractionmaster",
            name="wikidata_id",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="image_attribution",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="image_license",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'CC-BY-SA 4.0' — set only for images with a known open licence (Wikimedia), never for Google Photos.",
                max_length=60,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="image_source",
            field=models.URLField(
                blank=True,
                help_text="Link to the licensed image's source page (e.g. a Wikimedia Commons file page).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="osm_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="OSM 'type/id' form, e.g. 'way/123456789'.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hotelmaster",
            name="wikidata_id",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="image_attribution",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="image_license",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'CC-BY-SA 4.0' — set only for images with a known open licence (Wikimedia), never for Google Photos.",
                max_length=60,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="image_source",
            field=models.URLField(
                blank=True,
                help_text="Link to the licensed image's source page (e.g. a Wikimedia Commons file page).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="osm_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="OSM 'type/id' form, e.g. 'way/123456789'.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="restaurantmaster",
            name="wikidata_id",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="CategoryVocabularyMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("google", "Google Places"),
                            ("osm", "OpenStreetMap"),
                            ("wikidata", "Wikidata"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel"),
                            ("restaurant", "Restaurant"),
                            ("attraction", "Attraction"),
                            ("activity", "Activity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_value",
                    models.CharField(
                        help_text="e.g. Google type 'lodging', or OSM tag 'tourism=hotel'.",
                        max_length=100,
                    ),
                ),
                ("canonical_category", models.CharField(max_length=100)),
            ],
            options={
                "unique_together": {("source_system", "entity_type", "source_value")},
            },
        ),
    ]
