# Phase 7 (knowledge application migration, master plan §12): state-only
# relocation of 4 live models from apps.knowledge. The real tables
# (knowledge_distanceedge, knowledge_entityembedding, knowledge_localtip,
# knowledge_placeinsight) and — critically — the entity_embedding_hnsw
# pgvector index are untouched: database_operations is empty, this migration
# only tells Django's state that `reference` now owns these models. Paired
# with knowledge.0005_phase7_knowledge_migration (which forgets the same
# models from knowledge's state, also with empty database_operations).
# CreateModel bodies below were generated by `makemigrations` from the real
# model classes (apps/reference/models.py) and are unedited — only the
# SeparateDatabaseAndState wrapper below is hand-added.

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("reference", "0017_phase6_place_enrichment"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
        migrations.CreateModel(
            name="DistanceEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("origin_key", models.CharField(db_index=True, max_length=255)),
                ("destination_key", models.CharField(db_index=True, max_length=255)),
                ("mode", models.CharField(db_index=True, max_length=20)),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("duration_mins", models.FloatField(blank=True, null=True)),
                ("cost_estimate", models.JSONField(blank=True, null=True)),
                ("elevation_gain_m", models.FloatField(blank=True, null=True)),
                ("traffic_multiplier", models.FloatField(blank=True, null=True)),
                ("scenic_score", models.FloatField(blank=True, null=True)),
                ("carbon_kg", models.FloatField(blank=True, null=True)),
                ("source", models.CharField(max_length=30)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "knowledge_distanceedge",
                "unique_together": {("origin_key", "destination_key", "mode")},
            },
        ),
        migrations.CreateModel(
            name="EntityEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("object_id", models.CharField(max_length=64)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
                ("embedding_version", models.CharField(max_length=40)),
                ("source_text_hash", models.CharField(max_length=64)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_entityembedding",
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="entity_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
                "unique_together": {("content_type", "object_id", "embedding_version")},
            },
        ),
        migrations.CreateModel(
            name="LocalTip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("object_id", models.CharField(max_length=64)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("scam_warning", "scam_warning"),
                            ("after_dark", "after_dark"),
                            ("etiquette", "etiquette"),
                            ("emergency_prep", "emergency_prep"),
                            ("safety", "safety"),
                            ("money", "money"),
                            ("transport", "transport"),
                            ("food", "food"),
                        ],
                        max_length=40,
                    ),
                ),
                ("tip_text", models.TextField()),
                ("source", models.CharField(blank=True, max_length=60)),
                ("source_url", models.URLField(blank=True)),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("verified", "verified"),
                            ("estimated", "estimated"),
                            ("suggested", "suggested"),
                        ],
                        default="suggested",
                        max_length=12,
                    ),
                ),
                ("needs_human_review", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_localtip",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="knowledge_l_content_7c1b07_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlaceInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("object_id", models.CharField(max_length=64)),
                ("insight_type", models.CharField(max_length=40)),
                ("context_hash", models.CharField(db_index=True, max_length=64)),
                ("text", models.TextField(blank=True)),
                ("structured", models.JSONField(blank=True, default=dict)),
                ("provenance", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_placeinsight",
                "unique_together": {
                    ("content_type", "object_id", "insight_type", "context_hash")
                },
            },
        ),
        ], database_operations=[]),
    ]
