# Generated by Django 6.0.6 on 2026-07-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0018_phase7_knowledge_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="localtip",
            name="generation_method",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="localtip",
            name="source_inputs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="placeinsight",
            name="generation_method",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="placeinsight",
            name="source_inputs",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
