# Generated by Django 6.0.6 on 2026-06-22 08:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("currency", models.CharField(max_length=10)),
                ("timezone", models.CharField(max_length=100)),
                ("best_time_to_visit", models.TextField(blank=True)),
                ("popularity_score", models.FloatField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("place_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("museum", "Museum"),
                            ("temple", "Temple"),
                            ("monument", "Monument"),
                            ("restaurant", "Restaurant"),
                            ("park", "Park"),
                            ("beach", "Beach"),
                            ("shopping", "Shopping"),
                            ("entertainment", "Entertainment"),
                            ("tourist_attraction", "Tourist Attraction"),
                            ("amusement_park", "Amusement Park"),
                            ("local_activities", "Local Activities"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("country", models.CharField(db_index=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("review_count", models.IntegerField(default=0)),
                ("image_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("opening_hours", models.JSONField(blank=True, null=True)),
                (
                    "entry_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("price_level", models.IntegerField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("editorial_summary", models.TextField(blank=True, null=True)),
                (
                    "business_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "google_maps_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "formatted_phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "international_phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "wheelchair_accessible_entrance",
                    models.BooleanField(blank=True, null=True),
                ),
                ("reservable", models.BooleanField(blank=True, null=True)),
                ("serves_beer", models.BooleanField(blank=True, null=True)),
                ("serves_wine", models.BooleanField(blank=True, null=True)),
                ("serves_vegetarian_food", models.BooleanField(blank=True, null=True)),
                ("dine_in", models.BooleanField(blank=True, null=True)),
                ("takeout", models.BooleanField(blank=True, null=True)),
                ("delivery", models.BooleanField(blank=True, null=True)),
                ("secondary_images", models.JSONField(blank=True, default=list)),
                ("reviews", models.JSONField(blank=True, default=list)),
                ("ticket_info", models.JSONField(blank=True, null=True)),
                (
                    "estimated_duration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "ordering": ["-rating"],
                "indexes": [
                    models.Index(
                        fields=["city", "country"], name="attractions_city_886860_idx"
                    ),
                    models.Index(
                        fields=["category"], name="attractions_categor_2f4c97_idx"
                    ),
                ],
            },
        ),
    ]
