# Generated by Django 6.0.6 on 2026-06-26 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CanvasInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "canvas_type",
                    models.CharField(
                        choices=[
                            ("plan", "Plan"),
                            ("flight", "Flight"),
                            ("hotel", "Hotel"),
                            ("train", "Train"),
                            ("bus", "Bus"),
                            ("cab", "Cab"),
                            ("attraction", "Attraction"),
                            ("activity", "Activity"),
                            ("restaurant", "Restaurant"),
                            ("visa", "Visa"),
                            ("forex", "Forex"),
                            ("booking", "Booking"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("preview", "Preview"),
                            ("expanded", "Expanded"),
                            ("focused", "Focused"),
                        ],
                        default="preview",
                        max_length=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="CanvasData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "canvas_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="planner.canvasinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "canvas data",
                "verbose_name_plural": "canvas data",
            },
        ),
        migrations.CreateModel(
            name="PlannerWorkspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(default="New Trip", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                            ("booked", "Booked"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("exploring", "Exploring"),
                            ("booking", "Booking"),
                            ("review", "Review"),
                            ("traveling", "Traveling"),
                            ("completed", "Completed"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planner_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="PlannerTrip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField(blank=True)),
                (
                    "total_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "spent_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip",
                        to="planner.plannerworkspace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlannerMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("destination", models.JSONField(blank=True, default=dict)),
                ("origin", models.JSONField(blank=True, default=dict)),
                ("dates", models.JSONField(blank=True, default=dict)),
                ("travelers", models.JSONField(blank=True, default=dict)),
                ("budget", models.JSONField(blank=True, default=dict)),
                (
                    "transportation_preference",
                    models.JSONField(blank=True, default=list),
                ),
                ("hotel_preference", models.JSONField(blank=True, default=dict)),
                ("interests", models.JSONField(blank=True, default=list)),
                ("food_preference", models.JSONField(blank=True, default=dict)),
                ("accessibility", models.JSONField(blank=True, default=dict)),
                ("visa_status", models.JSONField(blank=True, default=dict)),
                ("booking_summary", models.JSONField(blank=True, default=dict)),
                (
                    "current_phase",
                    models.CharField(blank=True, default="initial", max_length=50),
                ),
                ("conversation_summary", models.TextField(blank=True)),
                ("last_ai_action", models.JSONField(blank=True, default=dict)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory",
                        to="planner.plannerworkspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "planner memory",
                "verbose_name_plural": "planner memories",
            },
        ),
        migrations.AddField(
            model_name="canvasinstance",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="canvas_instances",
                to="planner.plannerworkspace",
            ),
        ),
        migrations.CreateModel(
            name="BookingOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("item_type", models.CharField(max_length=30)),
                (
                    "source_canvas",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plan", "Plan"),
                            ("flight", "Flight"),
                            ("hotel", "Hotel"),
                            ("train", "Train"),
                            ("bus", "Bus"),
                            ("cab", "Cab"),
                            ("attraction", "Attraction"),
                            ("activity", "Activity"),
                            ("restaurant", "Restaurant"),
                            ("visa", "Visa"),
                            ("forex", "Forex"),
                            ("booking", "Booking"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("provider", models.CharField(blank=True, max_length=150)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_cart", "In Cart"),
                            ("processing", "Processing"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_cart",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_orders",
                        to="planner.plannerworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("type", models.CharField(max_length=50)),
                (
                    "canvas_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plan", "Plan"),
                            ("flight", "Flight"),
                            ("hotel", "Hotel"),
                            ("train", "Train"),
                            ("bus", "Bus"),
                            ("cab", "Cab"),
                            ("attraction", "Attraction"),
                            ("activity", "Activity"),
                            ("restaurant", "Restaurant"),
                            ("visa", "Visa"),
                            ("forex", "Forex"),
                            ("booking", "Booking"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("confidence", models.FloatField(default=0.8)),
                ("priority", models.IntegerField(default=5)),
                ("reason", models.TextField(blank=True)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "estimated_time",
                    models.PositiveIntegerField(
                        blank=True, help_text="Minutes", null=True
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("dependencies", models.JSONField(blank=True, default=list)),
                (
                    "actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{label, command_type, payload}]",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("is_accepted", models.BooleanField(default=False)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="planner.plannerworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "-confidence"],
            },
        ),
        migrations.CreateModel(
            name="SavedPlace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "place_cache",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reference.googleplacecache",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_places",
                        to="planner.plannerworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TripCity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("nights", models.PositiveIntegerField(default=1)),
                ("arrival_date", models.DateField(blank=True, null=True)),
                ("departure_date", models.DateField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_visits",
                        to="reference.city",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="planner.plannertrip",
                    ),
                ),
            ],
            options={
                "verbose_name": "trip city",
                "verbose_name_plural": "trip cities",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TripDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("day_number", models.PositiveIntegerField()),
                ("date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("preparation", "Preparation"),
                            ("travel", "Travel Day"),
                            ("exploration", "Exploration"),
                            ("return", "Return"),
                            ("rest", "Rest Day"),
                        ],
                        default="exploration",
                        max_length=20,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="days",
                        to="planner.tripcity",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="planner.plannertrip",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
            },
        ),
        migrations.CreateModel(
            name="TripActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("flight", "Flight"),
                            ("hotel", "Hotel"),
                            ("train", "Train"),
                            ("bus", "Bus"),
                            ("cab", "Cab"),
                            ("attraction", "Attraction"),
                            ("activity", "Activity"),
                            ("restaurant", "Restaurant"),
                            ("meal", "Meal"),
                            ("transfer", "Transfer"),
                            ("checkin", "Check-in"),
                            ("checkout", "Check-out"),
                            ("note", "Note"),
                            ("preparation", "Preparation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("location_name", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                (
                    "travel_time_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("transport_mode", models.CharField(blank=True, max_length=20)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("booked", "Booked"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("weather_info", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "booking_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline_activities",
                        to="planner.bookingorder",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="planner.tripday",
                    ),
                ),
            ],
            options={
                "verbose_name": "trip activity",
                "verbose_name_plural": "trip activities",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TripRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("transport_mode", models.CharField(blank=True, max_length=20)),
                (
                    "polyline",
                    models.TextField(
                        blank=True, help_text="Encoded polyline for map rendering"
                    ),
                ),
                ("route_data", models.JSONField(blank=True, default=dict)),
                (
                    "from_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_from",
                        to="planner.tripactivity",
                    ),
                ),
                (
                    "to_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_to",
                        to="planner.tripactivity",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="planner.plannertrip",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkspaceActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("event_type", models.CharField(max_length=100)),
                ("event_data", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="planner.plannerworkspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace activity",
                "verbose_name_plural": "workspace activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "widgets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Widget components to render",
                    ),
                ),
                (
                    "commands",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structured commands from AI",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="planner.plannerworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("origin_location", models.JSONField(blank=True, default=dict)),
                ("destination_location", models.JSONField(blank=True, default=dict)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("adults", models.PositiveSmallIntegerField(default=1)),
                ("children", models.PositiveSmallIntegerField(default=0)),
                ("infants", models.PositiveSmallIntegerField(default=0)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("budget_currency", models.CharField(default="INR", max_length=3)),
                (
                    "travel_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("budget", "Budget"),
                            ("mid_range", "Mid-range"),
                            ("luxury", "Luxury"),
                            ("backpacker", "Backpacker"),
                        ],
                        max_length=20,
                    ),
                ),
                ("interests", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context",
                        to="planner.plannerworkspace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterUniqueTogether(
            name="canvasinstance",
            unique_together={("workspace", "canvas_type")},
        ),
    ]
