# Generated by Django 6.0.6 on 2026-07-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="plannerchatmessage",
            new_name="planner_cha_workspa_cd59ac_idx",
            old_name="planner_cha_workspa_fcbfea_idx",
        ),
        migrations.RenameIndex(
            model_name="plannerworkspace",
            new_name="planner_wor_user_id_b73d18_idx",
            old_name="planner_wor_user_id_f48a1e_idx",
        ),
        migrations.RenameIndex(
            model_name="plannerworkspace",
            new_name="planner_wor_status_9765d0_idx",
            old_name="planner_wor_status_3abf3a_idx",
        ),
        migrations.AddField(
            model_name="tripdraftstate",
            name="intent",
            field=models.CharField(default="full_trip", max_length=50),
        ),
        migrations.AlterField(
            model_name="plannerworkspace",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                    ("saved", "Saved"),
                    ("booked", "Booked"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
