# Generated by Django 6.0.6 on 2026-07-03 03:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "planner",
            "0002_rename_planner_cha_workspa_fcbfea_idx_planner_cha_workspa_cd59ac_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannerQuestionBank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("destination_text", models.CharField(db_index=True, max_length=160)),
                ("missing_slots", models.JSONField(blank=True, default=list)),
                ("question_text", models.TextField()),
                ("widget_type", models.CharField(max_length=50)),
                ("widget_data", models.JSONField(blank=True, default=dict)),
                ("occurrence_count", models.IntegerField(default=1)),
                ("success_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "planner_question_bank",
                "ordering": ["-success_count", "-occurrence_count"],
            },
        ),
    ]
