# Generated by Django 6.0.6 on 2026-07-03 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_plannerquestionbank"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannerIntentFlow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("full_trip", "Full Trip"),
                            ("hotel_only", "Hotel Only"),
                            ("flight_only", "Flight Only"),
                            ("train_only", "Train Only"),
                            ("bus_only", "Bus Only"),
                            ("cab_only", "Cab / Taxi Only"),
                            ("cruise_only", "Cruise Only"),
                            ("car_rental", "Car Rental"),
                            ("transit_only", "Transit (Mixed)"),
                            ("activities_only", "Activities Only"),
                            ("food_and_dining", "Food & Dining"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "destination_text",
                    models.CharField(db_index=True, default="*", max_length=160),
                ),
                (
                    "conversation_steps",
                    models.JSONField(
                        default=list,
                        help_text="Ordered list of {slot, widget, message_index} steps",
                    ),
                ),
                (
                    "completion_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Fraction of sessions that led to plan creation",
                    ),
                ),
                ("usage_count", models.IntegerField(default=0)),
                (
                    "avg_messages_to_complete",
                    models.FloatField(
                        default=0.0,
                        help_text="Average number of messages to reach plan creation",
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "planner_intent_flow",
                "ordering": ["-completion_rate", "-usage_count"],
            },
        ),
        migrations.AddField(
            model_name="plannerquestionbank",
            name="intent",
            field=models.CharField(
                choices=[
                    ("full_trip", "Full Trip"),
                    ("hotel_only", "Hotel Only"),
                    ("flight_only", "Flight Only"),
                    ("train_only", "Train Only"),
                    ("bus_only", "Bus Only"),
                    ("cab_only", "Cab / Taxi Only"),
                    ("cruise_only", "Cruise Only"),
                    ("car_rental", "Car Rental"),
                    ("transit_only", "Transit (Mixed)"),
                    ("activities_only", "Activities Only"),
                    ("food_and_dining", "Food & Dining"),
                ],
                db_index=True,
                default="full_trip",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tripdraftstate",
            name="intent",
            field=models.CharField(
                choices=[
                    ("full_trip", "Full Trip"),
                    ("hotel_only", "Hotel Only"),
                    ("flight_only", "Flight Only"),
                    ("train_only", "Train Only"),
                    ("bus_only", "Bus Only"),
                    ("cab_only", "Cab / Taxi Only"),
                    ("cruise_only", "Cruise Only"),
                    ("car_rental", "Car Rental"),
                    ("transit_only", "Transit (Mixed)"),
                    ("activities_only", "Activities Only"),
                    ("food_and_dining", "Food & Dining"),
                ],
                default="full_trip",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="plannerquestionbank",
            index=models.Index(
                fields=["intent", "destination_text"],
                name="planner_que_intent_1204ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plannerintentflow",
            index=models.Index(
                fields=["intent", "destination_text"],
                name="planner_int_intent_e0d9bd_idx",
            ),
        ),
    ]
