# Generated by Django 6.0.6 on 2026-07-05 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_add_intent_flow_and_enhance_question_bank"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationDistanceCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("origin_key", models.CharField(db_index=True, max_length=255)),
                ("destination_key", models.CharField(db_index=True, max_length=255)),
                (
                    "mode",
                    models.CharField(db_index=True, default="driving", max_length=20),
                ),
                ("distance_km", models.FloatField(default=0.0)),
                ("duration_mins", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "planner_distance_cache",
                "indexes": [
                    models.Index(
                        fields=["origin_key", "destination_key", "mode"],
                        name="planner_dis_origin__f10804_idx",
                    )
                ],
                "unique_together": {("origin_key", "destination_key", "mode")},
            },
        ),
    ]
