# Generated by Django 6.0.6 on 2026-07-09 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0005_locationdistancecache"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannerworkspace",
            name="is_modified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PlannerTripOriginal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=160)),
                ("summary", models.TextField(blank=True)),
                ("cities", models.JSONField(blank=True, default=list)),
                ("days", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_trip",
                        to="planner.plannerworkspace",
                    ),
                ),
            ],
            options={
                "db_table": "planner_trip_original",
            },
        ),
    ]
