# Generated by Django 6.0.6 on 2026-07-09 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0006_plannerworkspace_is_modified_plannertriporiginal"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("kind", models.CharField(default="plan_edit", max_length=40)),
                ("title", models.CharField(max_length=200)),
                ("rationale", models.TextField(blank=True)),
                ("diff", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=300)),
                ("created_by", models.CharField(default="agent", max_length=20)),
                ("base_trip_updated_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="planner.plannerworkspace",
                    ),
                ),
            ],
            options={
                "db_table": "planner_plan_proposal",
                "ordering": ["-created_at"],
            },
        ),
    ]
