# Generated by Django 6.0.6 on 2026-07-09 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0007_planproposal"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanBlockCommitment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("block_id", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("priced", "Priced"),
                            ("held", "Held"),
                            ("booked", "Booked"),
                            ("ticketed", "Ticketed"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("quote", models.JSONField(blank=True, default=dict)),
                ("refundable_until", models.DateTimeField(blank=True, null=True)),
                ("provider_ref", models.CharField(blank=True, max_length=120)),
                ("history", models.JSONField(blank=True, default=list)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitments",
                        to="planner.plannerworkspace",
                    ),
                ),
            ],
            options={
                "db_table": "planner_block_commitment",
                "unique_together": {("workspace", "block_id")},
            },
        ),
    ]
