# Generated by Django 6.0.6 on 2026-07-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0010_plangenerationjob"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="locationdistancecache",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="locationdistancecache",
            name="planner_dis_origin__f10804_idx",
        ),
        migrations.DeleteModel(
            name="LocationDistanceCache",
        ),
    ]
