# Generated by Django 6.0.6 on 2026-07-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0011_alter_locationdistancecache_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planproposal",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
