# Generated by Django 6.0.6 on 2026-07-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0012_planproposal_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="plangenerationjob",
            name="degraded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plangenerationjob",
            name="usage",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
