# Generated by Django 6.0.6 on 2026-07-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0013_plangenerationjob_degraded_plangenerationjob_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannertrip",
            name="scorecard",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
