# Generated by Django 6.0.6 on 2026-07-19 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0019_jsonfield_decimal_encoder_remaining"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="plannerintentflow",
            name="planner_int_intent_e0d9bd_idx",
        ),
        migrations.DeleteModel(
            name="PlannerIntentFlow",
        ),
    ]
