# Phase 7 (knowledge application migration, master plan §12): state-only
# relocation of PlanInsightDismissal from apps.knowledge. The real table
# (knowledge_planinsightdismissal) is untouched — database_operations is
# empty, this migration only tells Django's state that `planner` now owns
# this model. Paired with knowledge.0005_phase7_knowledge_migration (which
# forgets the same model from knowledge's state, also with empty
# database_operations). The CreateModel body below was generated by
# `makemigrations` from the real model class (apps/planner/models.py) and is
# unedited — only the SeparateDatabaseAndState wrapper is hand-added.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0020_remove_planner_intent_flow"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
        migrations.CreateModel(
            name="PlanInsightDismissal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("context_hash", models.CharField(max_length=64)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_dismissals",
                        to="planner.plannerworkspace",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_planinsightdismissal",
                "unique_together": {("workspace", "context_hash")},
            },
        ),
        ], database_operations=[]),
    ]
